server:
  port: 8010
spring:
  application:
    name: service-feign
logging:
  level:
    root: info
    com.example: debug
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
